### ISSUE TITLE
Add CancelationToken.

### ISSUE THREAD

**Issue by kronic** [Yeah69/BFF.DataVirtualizingCollection#7]
```csharp
DataVirtualizingCollectionBuilder
				.Build<DetailModel>
				(
					100,
					_notificationScheduler,
					_defaultScheduler
				)
				.NonPreloading()
				.Hoarding()
				.TaskBasedFetchers((offset, count, CancellationToken cancellationToken) => , ( CancellationToken cancellationToken) => )
```

**and Add method CancelRequest{Async}**

**Comment by Yeah69** [comment]
For now I'll just assume that you are happy with the implementation sofar. But be warned I didn't put much effort into testing it sofar.

If you'll find some issues with the `CancellationToken`, you can either comment here (I'll reopen if possible) or open a new issue.
